//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.InvoiceServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceDetailsService", Namespace="http://schemas.datacontract.org/2004/07/IMSService.Entities")]
    [System.SerializableAttribute()]
    public partial class InvoiceDetailsService : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CGSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FinalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.ObjectModel.ObservableCollection<IMS.InvoiceServiceRef.Customer> ICustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal IGSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.ObjectModel.ObservableCollection<IMS.InvoiceServiceRef.ProductDetails> IProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InvoiceAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InvoiceDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SGSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SettlementAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Shipping_CGSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Shipping_IGSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Shipping_SGSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Shipping_TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VendorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CGST {
            get {
                return this.CGSTField;
            }
            set {
                if ((this.CGSTField.Equals(value) != true)) {
                    this.CGSTField = value;
                    this.RaisePropertyChanged("CGST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FinalStatus {
            get {
                return this.FinalStatusField;
            }
            set {
                if ((this.FinalStatusField.Equals(value) != true)) {
                    this.FinalStatusField = value;
                    this.RaisePropertyChanged("FinalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<IMS.InvoiceServiceRef.Customer> ICustomer {
            get {
                return this.ICustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.ICustomerField, value) != true)) {
                    this.ICustomerField = value;
                    this.RaisePropertyChanged("ICustomer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal IGST {
            get {
                return this.IGSTField;
            }
            set {
                if ((this.IGSTField.Equals(value) != true)) {
                    this.IGSTField = value;
                    this.RaisePropertyChanged("IGST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<IMS.InvoiceServiceRef.ProductDetails> IProduct {
            get {
                return this.IProductField;
            }
            set {
                if ((object.ReferenceEquals(this.IProductField, value) != true)) {
                    this.IProductField = value;
                    this.RaisePropertyChanged("IProduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InvoiceAmount {
            get {
                return this.InvoiceAmountField;
            }
            set {
                if ((this.InvoiceAmountField.Equals(value) != true)) {
                    this.InvoiceAmountField = value;
                    this.RaisePropertyChanged("InvoiceAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InvoiceDate {
            get {
                return this.InvoiceDateField;
            }
            set {
                if ((this.InvoiceDateField.Equals(value) != true)) {
                    this.InvoiceDateField = value;
                    this.RaisePropertyChanged("InvoiceDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceNo {
            get {
                return this.InvoiceNoField;
            }
            set {
                if ((this.InvoiceNoField.Equals(value) != true)) {
                    this.InvoiceNoField = value;
                    this.RaisePropertyChanged("InvoiceNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIDField, value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SGST {
            get {
                return this.SGSTField;
            }
            set {
                if ((this.SGSTField.Equals(value) != true)) {
                    this.SGSTField = value;
                    this.RaisePropertyChanged("SGST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SettlementAmount {
            get {
                return this.SettlementAmountField;
            }
            set {
                if ((this.SettlementAmountField.Equals(value) != true)) {
                    this.SettlementAmountField = value;
                    this.RaisePropertyChanged("SettlementAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Shipping_CGST {
            get {
                return this.Shipping_CGSTField;
            }
            set {
                if ((this.Shipping_CGSTField.Equals(value) != true)) {
                    this.Shipping_CGSTField = value;
                    this.RaisePropertyChanged("Shipping_CGST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Shipping_IGST {
            get {
                return this.Shipping_IGSTField;
            }
            set {
                if ((this.Shipping_IGSTField.Equals(value) != true)) {
                    this.Shipping_IGSTField = value;
                    this.RaisePropertyChanged("Shipping_IGST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Shipping_SGST {
            get {
                return this.Shipping_SGSTField;
            }
            set {
                if ((this.Shipping_SGSTField.Equals(value) != true)) {
                    this.Shipping_SGSTField = value;
                    this.RaisePropertyChanged("Shipping_SGST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Shipping_Total {
            get {
                return this.Shipping_TotalField;
            }
            set {
                if ((this.Shipping_TotalField.Equals(value) != true)) {
                    this.Shipping_TotalField = value;
                    this.RaisePropertyChanged("Shipping_Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Vendor {
            get {
                return this.VendorField;
            }
            set {
                if ((this.VendorField.Equals(value) != true)) {
                    this.VendorField = value;
                    this.RaisePropertyChanged("Vendor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/IMSService.Entities")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartyNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailID {
            get {
                return this.EmailIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIDField, value) != true)) {
                    this.EmailIDField = value;
                    this.RaisePropertyChanged("EmailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNo {
            get {
                return this.MobileNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNoField, value) != true)) {
                    this.MobileNoField = value;
                    this.RaisePropertyChanged("MobileNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartyName {
            get {
                return this.PartyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PartyNameField, value) != true)) {
                    this.PartyNameField = value;
                    this.RaisePropertyChanged("PartyName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDetails", Namespace="http://schemas.datacontract.org/2004/07/IMSService.Entities")]
    [System.SerializableAttribute()]
    public partial class ProductDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CGSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CGSTPercField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal IGSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal IGSTPercField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.ObjectModel.ObservableCollection<IMS.InvoiceServiceRef.SettlementDetails> ISettlementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InvoiceDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NetSaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SGSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SGSTPercField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SettlementAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Shipping_CGSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Shipping_IGSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Shipping_NetSaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Shipping_SGSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Shipping_TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Shipping_UnitPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaxGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal UnitPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CGST {
            get {
                return this.CGSTField;
            }
            set {
                if ((this.CGSTField.Equals(value) != true)) {
                    this.CGSTField = value;
                    this.RaisePropertyChanged("CGST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CGSTPerc {
            get {
                return this.CGSTPercField;
            }
            set {
                if ((this.CGSTPercField.Equals(value) != true)) {
                    this.CGSTPercField = value;
                    this.RaisePropertyChanged("CGSTPerc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal IGST {
            get {
                return this.IGSTField;
            }
            set {
                if ((this.IGSTField.Equals(value) != true)) {
                    this.IGSTField = value;
                    this.RaisePropertyChanged("IGST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal IGSTPerc {
            get {
                return this.IGSTPercField;
            }
            set {
                if ((this.IGSTPercField.Equals(value) != true)) {
                    this.IGSTPercField = value;
                    this.RaisePropertyChanged("IGSTPerc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<IMS.InvoiceServiceRef.SettlementDetails> ISettlement {
            get {
                return this.ISettlementField;
            }
            set {
                if ((object.ReferenceEquals(this.ISettlementField, value) != true)) {
                    this.ISettlementField = value;
                    this.RaisePropertyChanged("ISettlement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InvoiceDate {
            get {
                return this.InvoiceDateField;
            }
            set {
                if ((this.InvoiceDateField.Equals(value) != true)) {
                    this.InvoiceDateField = value;
                    this.RaisePropertyChanged("InvoiceDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceNo {
            get {
                return this.InvoiceNoField;
            }
            set {
                if ((this.InvoiceNoField.Equals(value) != true)) {
                    this.InvoiceNoField = value;
                    this.RaisePropertyChanged("InvoiceNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NetSale {
            get {
                return this.NetSaleField;
            }
            set {
                if ((this.NetSaleField.Equals(value) != true)) {
                    this.NetSaleField = value;
                    this.RaisePropertyChanged("NetSale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIDField, value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIDField, value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SGST {
            get {
                return this.SGSTField;
            }
            set {
                if ((this.SGSTField.Equals(value) != true)) {
                    this.SGSTField = value;
                    this.RaisePropertyChanged("SGST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SGSTPerc {
            get {
                return this.SGSTPercField;
            }
            set {
                if ((this.SGSTPercField.Equals(value) != true)) {
                    this.SGSTPercField = value;
                    this.RaisePropertyChanged("SGSTPerc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SettlementAmount {
            get {
                return this.SettlementAmountField;
            }
            set {
                if ((this.SettlementAmountField.Equals(value) != true)) {
                    this.SettlementAmountField = value;
                    this.RaisePropertyChanged("SettlementAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Shipping_CGST {
            get {
                return this.Shipping_CGSTField;
            }
            set {
                if ((this.Shipping_CGSTField.Equals(value) != true)) {
                    this.Shipping_CGSTField = value;
                    this.RaisePropertyChanged("Shipping_CGST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Shipping_IGST {
            get {
                return this.Shipping_IGSTField;
            }
            set {
                if ((this.Shipping_IGSTField.Equals(value) != true)) {
                    this.Shipping_IGSTField = value;
                    this.RaisePropertyChanged("Shipping_IGST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Shipping_NetSale {
            get {
                return this.Shipping_NetSaleField;
            }
            set {
                if ((this.Shipping_NetSaleField.Equals(value) != true)) {
                    this.Shipping_NetSaleField = value;
                    this.RaisePropertyChanged("Shipping_NetSale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Shipping_SGST {
            get {
                return this.Shipping_SGSTField;
            }
            set {
                if ((this.Shipping_SGSTField.Equals(value) != true)) {
                    this.Shipping_SGSTField = value;
                    this.RaisePropertyChanged("Shipping_SGST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Shipping_Total {
            get {
                return this.Shipping_TotalField;
            }
            set {
                if ((this.Shipping_TotalField.Equals(value) != true)) {
                    this.Shipping_TotalField = value;
                    this.RaisePropertyChanged("Shipping_Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Shipping_UnitPrice {
            get {
                return this.Shipping_UnitPriceField;
            }
            set {
                if ((this.Shipping_UnitPriceField.Equals(value) != true)) {
                    this.Shipping_UnitPriceField = value;
                    this.RaisePropertyChanged("Shipping_UnitPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringStatus {
            get {
                return this.StringStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StringStatusField, value) != true)) {
                    this.StringStatusField = value;
                    this.RaisePropertyChanged("StringStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxGroup {
            get {
                return this.TaxGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.TaxGroupField, value) != true)) {
                    this.TaxGroupField = value;
                    this.RaisePropertyChanged("TaxGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SettlementDetails", Namespace="http://schemas.datacontract.org/2004/07/IMSService.Entities")]
    [System.SerializableAttribute()]
    public partial class SettlementDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InvoiceDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SettlementAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SettlementDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SrNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InvoiceDate {
            get {
                return this.InvoiceDateField;
            }
            set {
                if ((this.InvoiceDateField.Equals(value) != true)) {
                    this.InvoiceDateField = value;
                    this.RaisePropertyChanged("InvoiceDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceNo {
            get {
                return this.InvoiceNoField;
            }
            set {
                if ((this.InvoiceNoField.Equals(value) != true)) {
                    this.InvoiceNoField = value;
                    this.RaisePropertyChanged("InvoiceNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIDField, value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIDField, value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SettlementAmount {
            get {
                return this.SettlementAmountField;
            }
            set {
                if ((this.SettlementAmountField.Equals(value) != true)) {
                    this.SettlementAmountField = value;
                    this.RaisePropertyChanged("SettlementAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SettlementDate {
            get {
                return this.SettlementDateField;
            }
            set {
                if ((this.SettlementDateField.Equals(value) != true)) {
                    this.SettlementDateField = value;
                    this.RaisePropertyChanged("SettlementDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SrNo {
            get {
                return this.SrNoField;
            }
            set {
                if ((this.SrNoField.Equals(value) != true)) {
                    this.SrNoField = value;
                    this.RaisePropertyChanged("SrNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringStatus {
            get {
                return this.StringStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StringStatusField, value) != true)) {
                    this.StringStatusField = value;
                    this.RaisePropertyChanged("StringStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataService", Namespace="http://schemas.datacontract.org/2004/07/IMSService.Services")]
    [System.SerializableAttribute()]
    public partial class DataService : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceCustomerDetails", Namespace="http://schemas.datacontract.org/2004/07/IMSService.Entities")]
    [System.SerializableAttribute()]
    public partial class InvoiceCustomerDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FinalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InvoiceDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VendorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailID {
            get {
                return this.EmailIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIDField, value) != true)) {
                    this.EmailIDField = value;
                    this.RaisePropertyChanged("EmailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FinalStatus {
            get {
                return this.FinalStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.FinalStatusField, value) != true)) {
                    this.FinalStatusField = value;
                    this.RaisePropertyChanged("FinalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InvoiceDate {
            get {
                return this.InvoiceDateField;
            }
            set {
                if ((this.InvoiceDateField.Equals(value) != true)) {
                    this.InvoiceDateField = value;
                    this.RaisePropertyChanged("InvoiceDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceNo {
            get {
                return this.InvoiceNoField;
            }
            set {
                if ((this.InvoiceNoField.Equals(value) != true)) {
                    this.InvoiceNoField = value;
                    this.RaisePropertyChanged("InvoiceNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNo {
            get {
                return this.MobileNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNoField, value) != true)) {
                    this.MobileNoField = value;
                    this.RaisePropertyChanged("MobileNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIDField, value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartyName {
            get {
                return this.PartyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PartyNameField, value) != true)) {
                    this.PartyNameField = value;
                    this.RaisePropertyChanged("PartyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vendor {
            get {
                return this.VendorField;
            }
            set {
                if ((object.ReferenceEquals(this.VendorField, value) != true)) {
                    this.VendorField = value;
                    this.RaisePropertyChanged("Vendor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TupleOfstringstringboolean", Namespace="http://schemas.datacontract.org/2004/07/System")]
    [System.SerializableAttribute()]
    public partial class TupleOfstringstringboolean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string m_Item1Field;
        
        private string m_Item2Field;
        
        private bool m_Item3Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_Item1 {
            get {
                return this.m_Item1Field;
            }
            set {
                if ((object.ReferenceEquals(this.m_Item1Field, value) != true)) {
                    this.m_Item1Field = value;
                    this.RaisePropertyChanged("m_Item1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_Item2 {
            get {
                return this.m_Item2Field;
            }
            set {
                if ((object.ReferenceEquals(this.m_Item2Field, value) != true)) {
                    this.m_Item2Field = value;
                    this.RaisePropertyChanged("m_Item2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool m_Item3 {
            get {
                return this.m_Item3Field;
            }
            set {
                if ((this.m_Item3Field.Equals(value) != true)) {
                    this.m_Item3Field = value;
                    this.RaisePropertyChanged("m_Item3");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InvoiceServiceRef.IInvoiceService")]
    public interface IInvoiceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoiceService/GetInvoiceDetails", ReplyAction="http://tempuri.org/IInvoiceService/GetInvoiceDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IMS.InvoiceServiceRef.DataService), Action="http://tempuri.org/IInvoiceService/GetInvoiceDetailsDataServiceFault", Name="DataService", Namespace="http://schemas.datacontract.org/2004/07/IMSService.Services")]
        System.Collections.ObjectModel.ObservableCollection<IMS.InvoiceServiceRef.InvoiceDetailsService> GetInvoiceDetails(int FromInvoiceNo, int ToInvoiceNo, System.DateTime FromInvoiceDate, System.DateTime ToInvoiceDate, string OrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoiceService/UpdateInvoiceDetails", ReplyAction="http://tempuri.org/IInvoiceService/UpdateInvoiceDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IMS.InvoiceServiceRef.DataService), Action="http://tempuri.org/IInvoiceService/UpdateInvoiceDetailsDataServiceFault", Name="DataService", Namespace="http://schemas.datacontract.org/2004/07/IMSService.Services")]
        bool UpdateInvoiceDetails(IMS.InvoiceServiceRef.InvoiceDetailsService invoiceDetails, IMS.InvoiceServiceRef.Customer customerDetails, int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoiceService/UpdateInvoiceProduct", ReplyAction="http://tempuri.org/IInvoiceService/UpdateInvoiceProductResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IMS.InvoiceServiceRef.DataService), Action="http://tempuri.org/IInvoiceService/UpdateInvoiceProductDataServiceFault", Name="DataService", Namespace="http://schemas.datacontract.org/2004/07/IMSService.Services")]
        bool UpdateInvoiceProduct(IMS.InvoiceServiceRef.ProductDetails productDetails, int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoiceService/UpdateInvoiceSettlement", ReplyAction="http://tempuri.org/IInvoiceService/UpdateInvoiceSettlementResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IMS.InvoiceServiceRef.DataService), Action="http://tempuri.org/IInvoiceService/UpdateInvoiceSettlementDataServiceFault", Name="DataService", Namespace="http://schemas.datacontract.org/2004/07/IMSService.Services")]
        bool UpdateInvoiceSettlement(IMS.InvoiceServiceRef.SettlementDetails settlementDetails, int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoiceService/DeleteInvoiceDetails", ReplyAction="http://tempuri.org/IInvoiceService/DeleteInvoiceDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IMS.InvoiceServiceRef.DataService), Action="http://tempuri.org/IInvoiceService/DeleteInvoiceDetailsDataServiceFault", Name="DataService", Namespace="http://schemas.datacontract.org/2004/07/IMSService.Services")]
        bool DeleteInvoiceDetails(IMS.InvoiceServiceRef.InvoiceDetailsService invoiceDetails, int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoiceService/DeleteInvoiceProduct", ReplyAction="http://tempuri.org/IInvoiceService/DeleteInvoiceProductResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IMS.InvoiceServiceRef.DataService), Action="http://tempuri.org/IInvoiceService/DeleteInvoiceProductDataServiceFault", Name="DataService", Namespace="http://schemas.datacontract.org/2004/07/IMSService.Services")]
        bool DeleteInvoiceProduct(IMS.InvoiceServiceRef.ProductDetails productDetails, int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoiceService/DeleteInvoiceSettlement", ReplyAction="http://tempuri.org/IInvoiceService/DeleteInvoiceSettlementResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IMS.InvoiceServiceRef.DataService), Action="http://tempuri.org/IInvoiceService/DeleteInvoiceSettlementDataServiceFault", Name="DataService", Namespace="http://schemas.datacontract.org/2004/07/IMSService.Services")]
        bool DeleteInvoiceSettlement(IMS.InvoiceServiceRef.SettlementDetails settlementDetails, int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoiceService/FindGstRate", ReplyAction="http://tempuri.org/IInvoiceService/FindGstRateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IMS.InvoiceServiceRef.DataService), Action="http://tempuri.org/IInvoiceService/FindGstRateDataServiceFault", Name="DataService", Namespace="http://schemas.datacontract.org/2004/07/IMSService.Services")]
        decimal FindGstRate(string ProductID, string TaxType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoiceService/InvoiceDetailsPatch", ReplyAction="http://tempuri.org/IInvoiceService/InvoiceDetailsPatchResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IMS.InvoiceServiceRef.DataService), Action="http://tempuri.org/IInvoiceService/InvoiceDetailsPatchDataServiceFault", Name="DataService", Namespace="http://schemas.datacontract.org/2004/07/IMSService.Services")]
        System.Collections.ObjectModel.ObservableCollection<IMS.InvoiceServiceRef.InvoiceCustomerDetails> InvoiceDetailsPatch(int FromInvoiceNo, int ToInvoiceNo, System.DateTime FromInvoiceDate, System.DateTime ToInvoiceDate, int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoiceService/InvoiceProductPatch", ReplyAction="http://tempuri.org/IInvoiceService/InvoiceProductPatchResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IMS.InvoiceServiceRef.DataService), Action="http://tempuri.org/IInvoiceService/InvoiceProductPatchDataServiceFault", Name="DataService", Namespace="http://schemas.datacontract.org/2004/07/IMSService.Services")]
        System.Collections.ObjectModel.ObservableCollection<IMS.InvoiceServiceRef.ProductDetails> InvoiceProductPatch(int FromInvoiceNo, int ToInvoiceNo, System.DateTime FromInvoiceDate, System.DateTime ToInvoiceDate, string ProductID, int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoiceService/InvoiceSettlementPatch", ReplyAction="http://tempuri.org/IInvoiceService/InvoiceSettlementPatchResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IMS.InvoiceServiceRef.DataService), Action="http://tempuri.org/IInvoiceService/InvoiceSettlementPatchDataServiceFault", Name="DataService", Namespace="http://schemas.datacontract.org/2004/07/IMSService.Services")]
        System.Collections.ObjectModel.ObservableCollection<IMS.InvoiceServiceRef.SettlementDetails> InvoiceSettlementPatch(int FromInvoiceNo, int ToInvoiceNo, System.DateTime FromInvoiceDate, System.DateTime ToInvoiceDate, string ProductID, System.DateTime FromSettlementDate, System.DateTime ToSettlementDate, int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoiceService/UploadPatchSheet", ReplyAction="http://tempuri.org/IInvoiceService/UploadPatchSheetResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IMS.InvoiceServiceRef.DataService), Action="http://tempuri.org/IInvoiceService/UploadPatchSheetDataServiceFault", Name="DataService", Namespace="http://schemas.datacontract.org/2004/07/IMSService.Services")]
        IMS.InvoiceServiceRef.TupleOfstringstringboolean UploadPatchSheet(byte[] sheetData, string FileName, int UserID, int SheetType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoiceService/UploadSheetUpdateDelete", ReplyAction="http://tempuri.org/IInvoiceService/UploadSheetUpdateDeleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IMS.InvoiceServiceRef.DataService), Action="http://tempuri.org/IInvoiceService/UploadSheetUpdateDeleteDataServiceFault", Name="DataService", Namespace="http://schemas.datacontract.org/2004/07/IMSService.Services")]
        IMS.InvoiceServiceRef.TupleOfstringstringboolean UploadSheetUpdateDelete(byte[] sheetData, string FileName, int UserID, int SheetType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInvoiceServiceChannel : IMS.InvoiceServiceRef.IInvoiceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InvoiceServiceClient : System.ServiceModel.ClientBase<IMS.InvoiceServiceRef.IInvoiceService>, IMS.InvoiceServiceRef.IInvoiceService {
        
        public InvoiceServiceClient() {
        }
        
        public InvoiceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InvoiceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvoiceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvoiceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.ObjectModel.ObservableCollection<IMS.InvoiceServiceRef.InvoiceDetailsService> GetInvoiceDetails(int FromInvoiceNo, int ToInvoiceNo, System.DateTime FromInvoiceDate, System.DateTime ToInvoiceDate, string OrderID) {
            return base.Channel.GetInvoiceDetails(FromInvoiceNo, ToInvoiceNo, FromInvoiceDate, ToInvoiceDate, OrderID);
        }
        
        public bool UpdateInvoiceDetails(IMS.InvoiceServiceRef.InvoiceDetailsService invoiceDetails, IMS.InvoiceServiceRef.Customer customerDetails, int UserID) {
            return base.Channel.UpdateInvoiceDetails(invoiceDetails, customerDetails, UserID);
        }
        
        public bool UpdateInvoiceProduct(IMS.InvoiceServiceRef.ProductDetails productDetails, int UserID) {
            return base.Channel.UpdateInvoiceProduct(productDetails, UserID);
        }
        
        public bool UpdateInvoiceSettlement(IMS.InvoiceServiceRef.SettlementDetails settlementDetails, int UserID) {
            return base.Channel.UpdateInvoiceSettlement(settlementDetails, UserID);
        }
        
        public bool DeleteInvoiceDetails(IMS.InvoiceServiceRef.InvoiceDetailsService invoiceDetails, int UserID) {
            return base.Channel.DeleteInvoiceDetails(invoiceDetails, UserID);
        }
        
        public bool DeleteInvoiceProduct(IMS.InvoiceServiceRef.ProductDetails productDetails, int UserID) {
            return base.Channel.DeleteInvoiceProduct(productDetails, UserID);
        }
        
        public bool DeleteInvoiceSettlement(IMS.InvoiceServiceRef.SettlementDetails settlementDetails, int UserID) {
            return base.Channel.DeleteInvoiceSettlement(settlementDetails, UserID);
        }
        
        public decimal FindGstRate(string ProductID, string TaxType) {
            return base.Channel.FindGstRate(ProductID, TaxType);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<IMS.InvoiceServiceRef.InvoiceCustomerDetails> InvoiceDetailsPatch(int FromInvoiceNo, int ToInvoiceNo, System.DateTime FromInvoiceDate, System.DateTime ToInvoiceDate, int UserID) {
            return base.Channel.InvoiceDetailsPatch(FromInvoiceNo, ToInvoiceNo, FromInvoiceDate, ToInvoiceDate, UserID);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<IMS.InvoiceServiceRef.ProductDetails> InvoiceProductPatch(int FromInvoiceNo, int ToInvoiceNo, System.DateTime FromInvoiceDate, System.DateTime ToInvoiceDate, string ProductID, int UserID) {
            return base.Channel.InvoiceProductPatch(FromInvoiceNo, ToInvoiceNo, FromInvoiceDate, ToInvoiceDate, ProductID, UserID);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<IMS.InvoiceServiceRef.SettlementDetails> InvoiceSettlementPatch(int FromInvoiceNo, int ToInvoiceNo, System.DateTime FromInvoiceDate, System.DateTime ToInvoiceDate, string ProductID, System.DateTime FromSettlementDate, System.DateTime ToSettlementDate, int UserID) {
            return base.Channel.InvoiceSettlementPatch(FromInvoiceNo, ToInvoiceNo, FromInvoiceDate, ToInvoiceDate, ProductID, FromSettlementDate, ToSettlementDate, UserID);
        }
        
        public IMS.InvoiceServiceRef.TupleOfstringstringboolean UploadPatchSheet(byte[] sheetData, string FileName, int UserID, int SheetType) {
            return base.Channel.UploadPatchSheet(sheetData, FileName, UserID, SheetType);
        }
        
        public IMS.InvoiceServiceRef.TupleOfstringstringboolean UploadSheetUpdateDelete(byte[] sheetData, string FileName, int UserID, int SheetType) {
            return base.Channel.UploadSheetUpdateDelete(sheetData, FileName, UserID, SheetType);
        }
    }
}
